language: php

php:
  - 7.2

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml
  - ls build/logs/

after_script:
  - php vendor/bin/coveralls -v
